services:
    autopsy:
        image: eecs388/autopsy
        restart: always
        # Allocate sufficient memory to the Autopsy GUI process.
        # If your machine is running out of memory, you might try decreasing this,
        # though Autopsy may run into instability if you do so.
        shm_size: 2g
        # Access Autopsy via http://localhost:38815 in your browser,
        # or by vnc://localhost:38865 in a VNC client.
        ports:
            - 38815:5800
            - 38865:5900
        volumes:
            - ..:/workspaces/lab5
        environment:
            # Some sensible defaults to give Autopsy's interface enough room to breathe.
            # Feel free to change as you wish.
            - DISPLAY_WIDTH=1920
            - DISPLAY_HEIGHT=1080
    workspace:
        build: .
        volumes:
            - ..:/workspaces/lab5
        # Prevent container from instantly exiting, allowing us to attach terminal
        command: /bin/sh -c "sleep infinity"
